import { render } from "solid-js/web";
import App from "./App";
import { installActionRegistry } from "./lib/actions";
import { installAutomation } from "./lib/automation";
import { installAutomationLive } from "./lib/automation-live";
import { installCommandPalette } from "./lib/command-palette";
import { installConversionRecipes } from "./lib/conversion-recipes";
import { installConverters } from "./lib/converters";
import { installCustomActions } from "./lib/custom-actions";
import { installDiskMap } from "./lib/disk-map";
import { installDuplicateFinder } from "./lib/duplicates";
import { installFileHealth } from "./lib/file-health";
import { installFootprints } from "./lib/footprints";
import { installGlobalSearch } from "./lib/global-search";
import { installImageThumbnails } from "./lib/thumbnails";
import { installImageTools } from "./lib/image-tools";
import { installInspector } from "./lib/inspector";
import { installInternalPointerDrag } from "./lib/internal-drag";
import { installNativeFileDrop } from "./lib/native-drop";
import { installOperationQueue } from "./lib/operation-queue";
import { installPdfTools } from "./lib/pdf-tools";
import { installPortal } from "./lib/portal";
import { installQolActions } from "./lib/qol-actions";
import { installQolBridge } from "./lib/qol-bridge";
import { installQolPack2 } from "./lib/qol-pack2";
import { installQolPack3 } from "./lib/qol-pack3";
import { installQuickLook } from "./lib/quick-look";
import { installSimilarPhotos } from "./lib/similar-photos";
import { installSmartExtract } from "./lib/smart-extract";
import { installTagCollections } from "./lib/tag-collections";
import { installTags } from "./lib/tags";
import { installTerminalActions } from "./lib/terminal-actions";
import { installUtilities } from "./lib/utilities";
import { installUxInteractions } from "./lib/ux-interactions";
import { installViewPreferences } from "./lib/view-preferences";
import "./styles.css";
import "./native-drop.css";
import "./internal-drag.css";
import "./quick-look.css";
import "./rich-previews.css";
import "./thumbnails.css";
import "./global-search.css";
import "./utilities.css";
import "./duplicates.css";
import "./disk-map.css";
import "./image-tools.css";
import "./similar-photos.css";
import "./portal.css";
import "./converters.css";
import "./footprints.css";
import "./pdf-tools.css";
import "./operation-queue.css";
import "./automation.css";
import "./view-polish.css";
import "./column-browser.css";
import "./menu-polish.css";
import "./quality-polish.css";
import "./ux-interactions.css";
import "./m6.css";
import "./file-health.css";
import "./tag-collections.css";
import "./custom-actions.css";

const root = document.getElementById("root");

if (!root) {
  throw new Error("Scout root element was not found");
}

const actionRegistryCleanup = installActionRegistry();
const qolActionsCleanup = installQolActions();
const qolBridgeCleanup = installQolBridge();
const qolPack2Cleanup = installQolPack2();
const qolPack3Cleanup = installQolPack3();
const viewPreferencesCleanup = installViewPreferences();
const commandPaletteCleanup = installCommandPalette();
const inspectorCleanup = installInspector();
const fileHealthCleanup = installFileHealth();
const nativeDropCleanup = installNativeFileDrop();
const internalDragCleanup = installInternalPointerDrag();
const quickLookCleanup = installQuickLook();
const uxInteractionsCleanup = installUxInteractions();
const thumbnailCleanup = installImageThumbnails();
const globalSearchCleanup = installGlobalSearch();
const utilitiesCleanup = installUtilities();
const smartExtractCleanup = installSmartExtract();
const conversionRecipesCleanup = installConversionRecipes();
const customActionsCleanup = installCustomActions();
const duplicateFinderCleanup = installDuplicateFinder();
const diskMapCleanup = installDiskMap();
const imageToolsCleanup = installImageTools();
const similarPhotosCleanup = installSimilarPhotos();
const portalCleanup = installPortal();
const convertersCleanup = installConverters();
const tagsCleanup = installTags();
const tagCollectionsCleanup = installTagCollections();
const terminalActionsCleanup = installTerminalActions();
const footprintsCleanup = installFootprints();
const pdfToolsCleanup = installPdfTools();
const operationQueueCleanup = installOperationQueue();
const automationCleanup = installAutomation();
const automationLiveCleanup = installAutomationLive();

if (import.meta.hot) {
  import.meta.hot.dispose(() => {
    internalDragCleanup();
    quickLookCleanup();
    uxInteractionsCleanup();
    thumbnailCleanup();
    globalSearchCleanup();
    utilitiesCleanup();
    smartExtractCleanup();
    conversionRecipesCleanup();
    customActionsCleanup();
    duplicateFinderCleanup();
    diskMapCleanup();
    imageToolsCleanup();
    similarPhotosCleanup();
    portalCleanup();
    convertersCleanup();
    tagCollectionsCleanup();
    tagsCleanup();
    terminalActionsCleanup();
    footprintsCleanup();
    pdfToolsCleanup();
    operationQueueCleanup();
    automationCleanup();
    automationLiveCleanup();
    fileHealthCleanup();
    inspectorCleanup();
    commandPaletteCleanup();
    viewPreferencesCleanup();
    qolPack3Cleanup();
    qolPack2Cleanup();
    qolBridgeCleanup();
    qolActionsCleanup();
    actionRegistryCleanup();
    void nativeDropCleanup.then((cleanup) => cleanup());
  });
}

render(() => <App />, root);
