import { render } from "solid-js/web";
import App from "./App";
import { installActionRegistry } from "./lib/actions";
import { installAutomation } from "./lib/automation";
import { installAutomationLive } from "./lib/automation-live";
import { installBackgroundContextMenu } from "./lib/background-context-menu";
import { installBreadcrumbScroll } from "./lib/breadcrumb-scroll";
import { installCommandPalette } from "./lib/command-palette";
import { installContextMenuKeyboard } from "./lib/context-menu-keyboard";
import { installConversionRecipes } from "./lib/conversion-recipes";
import { installConverters } from "./lib/converters";
import { installCustomActions } from "./lib/custom-actions";
import { installDiskMap } from "./lib/disk-map";
import { installDragAutoscroll } from "./lib/drag-autoscroll";
import { installDuplicateFinder } from "./lib/duplicates";
import { installFileHealth } from "./lib/file-health";
import { installFootprints } from "./lib/footprints";
import { installGitAmbient } from "./lib/git-ambient";
import { installGitIntegration } from "./lib/git-integration";
import { installGlobalSearch } from "./lib/global-search";
import { installImageThumbnails } from "./lib/thumbnails";
import { installImageTools } from "./lib/image-tools";
import { installInspector } from "./lib/inspector";
import { installInternalPointerDrag } from "./lib/internal-drag";
import { installListColumnResize } from "./lib/list-column-resize";
import { installModalFocusContract } from "./lib/modal-focus";
import { installMouseNavigation } from "./lib/mouse-navigation";
import { installNativeFileDrop } from "./lib/native-drop";
import { installNavigationGestures } from "./lib/navigation-gestures";
import { installNavigationMemory } from "./lib/navigation-memory";
import { installNavigationUx3 } from "./lib/navigation-ux3";
import { installOperationQueue } from "./lib/operation-queue";
import { installPaneResize } from "./lib/pane-resize";
import { installPdfTools } from "./lib/pdf-tools";
import { installPlatformNavigationShortcuts } from "./lib/platform-navigation-shortcuts";
import { installPortal } from "./lib/portal";
import { installQolActions } from "./lib/qol-actions";
import { installQolBridge } from "./lib/qol-bridge";
import { installQolPack2 } from "./lib/qol-pack2";
import { installQolPack3 } from "./lib/qol-pack3";
import { installQuickLook } from "./lib/quick-look";
import { installSearchInteractions } from "./lib/search-interactions";
import { installSessionContinuity } from "./lib/session-continuity";
import { installSidebarDisclosure } from "./lib/sidebar-disclosure";
import { installSidebarDropTargets } from "./lib/sidebar-drop-targets";
import { installSidebarKeyboardNavigation } from "./lib/sidebar-keyboard";
import { installSidebarOrder } from "./lib/sidebar-order";
import { installSidebarResize } from "./lib/sidebar-resize";
import { installSidebarVisibility } from "./lib/sidebar-visibility";
import { installSimilarPhotos } from "./lib/similar-photos";
import { installSmartExtract } from "./lib/smart-extract";
import { installTabAccessibility } from "./lib/tab-accessibility";
import { installTabDrag } from "./lib/tab-drag";
import { installTabDropTargets } from "./lib/tab-drop-targets";
import { installTabKeyboardNavigation } from "./lib/tab-keyboard-navigation";
import { installTabScroll } from "./lib/tab-scroll";
import { installTagCollections } from "./lib/tag-collections";
import { installTags } from "./lib/tags";
import { installTerminalActions } from "./lib/terminal-actions";
import { installToolbarMenuKeyboard } from "./lib/toolbar-menu-keyboard";
import { installUtilities } from "./lib/utilities";
import { installUxInteractions } from "./lib/ux-interactions";
import { installViewPreferences } from "./lib/view-preferences";
import "./styles.css";
import "./native-drop.css";
import "./internal-drag.css";
import "./quick-look.css";
import "./rich-previews.css";
import "./thumbnails.css";
import "./global-search.css";
import "./utilities.css";
import "./duplicates.css";
import "./disk-map.css";
import "./image-tools.css";
import "./similar-photos.css";
import "./portal.css";
import "./converters.css";
import "./footprints.css";
import "./pdf-tools.css";
import "./operation-queue.css";
import "./automation.css";
import "./view-polish.css";
import "./column-browser.css";
import "./menu-polish.css";
import "./quality-polish.css";
import "./ux-interactions.css";
import "./ux2.css";
import "./navigation-ux3.css";
import "./m6.css";
import "./file-health.css";
import "./tag-collections.css";
import "./custom-actions.css";
import "./git-integration.css";
import "./git-ambient.css";
import "./tab-scroll.css";
import "./sidebar-scroll.css";
import "./sidebar-resize.css";
import "./sidebar-disclosure.css";
import "./sidebar-visibility.css";
import "./sidebar-order.css";
import "./pane-resize.css";
import "./breadcrumb-scroll.css";
import "./context-menu-keyboard.css";
import "./list-column-resize.css";
import "./tab-accessibility.css";

const root = document.getElementById("root");

if (!root) {
  throw new Error("Scout root element was not found");
}

const modalFocusCleanup = installModalFocusContract();
const actionRegistryCleanup = installActionRegistry();
const qolActionsCleanup = installQolActions();
const qolBridgeCleanup = installQolBridge();
const qolPack2Cleanup = installQolPack2();
const qolPack3Cleanup = installQolPack3();
const viewPreferencesCleanup = installViewPreferences();
const commandPaletteCleanup = installCommandPalette();
const contextMenuKeyboardCleanup = installContextMenuKeyboard();
const toolbarMenuKeyboardCleanup = installToolbarMenuKeyboard();
const backgroundContextMenuCleanup = installBackgroundContextMenu();
const inspectorCleanup = installInspector();
const fileHealthCleanup = installFileHealth();
const gitIntegrationCleanup = installGitIntegration();
const gitAmbientCleanup = installGitAmbient();
const mouseNavigationCleanup = installMouseNavigation();
const navigationGesturesCleanup = installNavigationGestures();
const navigationMemoryCleanup = installNavigationMemory();
const sessionContinuityCleanup = installSessionContinuity();
const navigationUx3Cleanup = installNavigationUx3();
const breadcrumbScrollCleanup = installBreadcrumbScroll();
const listColumnResizeCleanup = installListColumnResize();
const platformNavigationShortcutsCleanup = installPlatformNavigationShortcuts();
const searchInteractionsCleanup = installSearchInteractions();
const sidebarResizeCleanup = installSidebarResize();
const sidebarVisibilityCleanup = installSidebarVisibility();
const sidebarDisclosureCleanup = installSidebarDisclosure();
const sidebarKeyboardCleanup = installSidebarKeyboardNavigation();
const sidebarOrderCleanup = installSidebarOrder();
const sidebarDropTargetsCleanup = installSidebarDropTargets();
const paneResizeCleanup = installPaneResize();
const tabDropTargetsCleanup = installTabDropTargets();
const tabKeyboardNavigationCleanup = installTabKeyboardNavigation();
const tabAccessibilityCleanup = installTabAccessibility();
const tabScrollCleanup = installTabScroll();
const dragAutoscrollCleanup = installDragAutoscroll();
const nativeDropCleanup = installNativeFileDrop();
const internalDragCleanup = installInternalPointerDrag();
const tabDragCleanup = installTabDrag();
const quickLookCleanup = installQuickLook();
const uxInteractionsCleanup = installUxInteractions();
const thumbnailCleanup = installImageThumbnails();
const globalSearchCleanup = installGlobalSearch();
const utilitiesCleanup = installUtilities();
const smartExtractCleanup = installSmartExtract();
const conversionRecipesCleanup = installConversionRecipes();
const customActionsCleanup = installCustomActions();
const duplicateFinderCleanup = installDuplicateFinder();
const diskMapCleanup = installDiskMap();
const imageToolsCleanup = installImageTools();
const similarPhotosCleanup = installSimilarPhotos();
const portalCleanup = installPortal();
const convertersCleanup = installConverters();
const tagsCleanup = installTags();
const tagCollectionsCleanup = installTagCollections();
const terminalActionsCleanup = installTerminalActions();
const footprintsCleanup = installFootprints();
const pdfToolsCleanup = installPdfTools();
const operationQueueCleanup = installOperationQueue();
const automationCleanup = installAutomation();
const automationLiveCleanup = installAutomationLive();

if (import.meta.hot) {
  import.meta.hot.dispose(() => {
    internalDragCleanup();
    dragAutoscrollCleanup();
    tabScrollCleanup();
    tabAccessibilityCleanup();
    tabKeyboardNavigationCleanup();
    tabDragCleanup();
    quickLookCleanup();
    uxInteractionsCleanup();
    thumbnailCleanup();
    globalSearchCleanup();
    utilitiesCleanup();
    smartExtractCleanup();
    conversionRecipesCleanup();
    customActionsCleanup();
    duplicateFinderCleanup();
    diskMapCleanup();
    imageToolsCleanup();
    similarPhotosCleanup();
    portalCleanup();
    convertersCleanup();
    tagCollectionsCleanup();
    tagsCleanup();
    terminalActionsCleanup();
    footprintsCleanup();
    pdfToolsCleanup();
    operationQueueCleanup();
    automationCleanup();
    automationLiveCleanup();
    paneResizeCleanup();
    tabDropTargetsCleanup();
    sidebarDropTargetsCleanup();
    sidebarOrderCleanup();
    sidebarKeyboardCleanup();
    sidebarDisclosureCleanup();
    sidebarVisibilityCleanup();
    sidebarResizeCleanup();
    searchInteractionsCleanup();
    platformNavigationShortcutsCleanup();
    listColumnResizeCleanup();
    breadcrumbScrollCleanup();
    sessionContinuityCleanup();
    navigationMemoryCleanup();
    navigationUx3Cleanup();
    navigationGesturesCleanup();
    mouseNavigationCleanup();
    gitAmbientCleanup();
    gitIntegrationCleanup();
    fileHealthCleanup();
    inspectorCleanup();
    backgroundContextMenuCleanup();
    toolbarMenuKeyboardCleanup();
    contextMenuKeyboardCleanup();
    commandPaletteCleanup();
    viewPreferencesCleanup();
    qolPack3Cleanup();
    qolPack2Cleanup();
    qolBridgeCleanup();
    qolActionsCleanup();
    actionRegistryCleanup();
    modalFocusCleanup();
    void nativeDropCleanup.then((cleanup) => cleanup());
  });
}

render(() => <App />, root);